### PR TITLE
Ian test

### PR DESCRIPTION
**Pull request by thebigg73**
Ian this has the new preference boolean (stickyBlockInfo) added, with the preference switchable from PopUpExtraInfoFragment.java / popup_extrainfo.xml.
You can get there running the app from Settings/Display/Extra information.
Currently the string for the option in the layout xml is 'Songsheet', however, we could easily change it to @string/extra if you wanted it to say 'Extra information' instead.   These strings already have the necessary translations in the app.
I updated the reference to this preference in Preferences.java and its use in ProcessSong.java.

### CODE REVIEW

**Review by thebigg73 — COMMENTED** [review]
There are a couple of other files showing changes.  Most are just removal of old commented sections that aren't used and a if !=null block added in to PresenterMode.

**Comment by iv-gha** [comment]
Thanks Gareth.

**Comment by thebigg73** [comment]
Hi Ian

I found the pdf export I was working on (text based) - it was in the
material app!  I've attached it to show how it looks.  You'll see the
monospace font use, but that I will be able to easily integrate your info
block into this.  This could be the export version, rather than worrying
about PNG/pdf printing?

**Comment by iv-gha** [comment]
I am not getting the attachment,.  I attached using the github comment form and that worked when I sent you the example PDF earlier.  Perhaps that is a way to get it to me.

Thanks
Ian

**Comment by thebigg73** [comment]
I'll do that.  I didn't see your attachment until I viewed it on the GitHub
site comment trail either.  I've promised my wife a night away from the
computer (on my phone just now), so I'll send it tomorrow - no rush.

Cheers,
Gareth

**Comment by iv-gha** [comment]
Hello Gareth,
I have worked on the extra info issues. I intro 'hidden from the user' H__1 and F__1 header and footer sections with handling to display  in presentation order as well! Song block only for presentation mode and move others to the bottom in stage mode. This is committed in my fork.

I have also continued working on a fix for lyrics appearing too close to chords.... so
```
             A
song with a     break

rendering as 
             A
song with a   break
```

This is a render change so needs care.

Recognising it has been fairly intense for a while - take a look as and when.  Should I pull?

Kind regards
Ian V

**Comment by thebigg73** [comment]
Hi Ian,
I'll create a pull to the test branch in a moment.

The OpenSong/ChordPro conversion issues are if songs are formatted like:
`[Intro]
. |G   C |  G   D |
 issue with this one

[V1]
.G///C///G///D///
`
[MAIN_Give thanks.pdf](https://github.com/iv-gha/OpenSongTablet/files/5074956/MAIN_Give.thanks.pdf)
[MAIN_Gifted response (we will worship You).pdf](https://github.com/iv-gha/OpenSongTablet/files/5074958/MAIN_Gifted.response.we.will.worship.You.pdf)

Also, here are a couple of examples of text based pdf rendered in OpenSongApp.  Hopefully you'll see them on GitHub now.

**Comment by iv-gha** [comment]
Hello Gareth,

If I convert the examples I get

```
#[Intro]
 [|G]   [C]  [|]  [G]  [D|]
[G///C///G///D///]
```
Which is what I expect as this is each 'word' surrounded by brackets with appropriate spaces..  They convert back and forth.
Have I fixed this already! (I remember removing treating '|' as a space for the chord positions algorithm to get them recognised as part of words).

There is the case of '||' use on chord lines which I have not looked at - these get removed as they are considered split points?  I use }| and |{ instead.  So a slightly non standard notation of.
`
𝅘𝅥𝅮    }| G  | A  | F  |{
`
with a 'fun' note symbol thrown in!

Kind regards
Ian V

**Comment by iv-gha** [comment]
I have seen the monospaced approach on the internet, most ('songselect' etc) use the proportional font style.  It is certainly my wish to have good proportional font song sheets so do keep the 'print screen' png approach.

**Comment by iv-gha** [comment]
Going back a little... I think songsheet is fine for the option.  We could further improve by moving copyright to the bottom, indenting choruses and adding CCLI info.  So 'song select'!

**Pull request merged**
